# Generated by Django 6.0.2 on 2026-02-28 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, help_text='ChatSession UUID if linked', null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('class_no', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, choices=[('science', 'Science'), ('social_science', 'Social Science')], max_length=20, null=True)),
                ('language', models.CharField(default='english', max_length=10)),
                ('has_image', models.BooleanField(default=False)),
                ('sources', models.JSONField(default=list, help_text='Pinecone chunks used for this answer')),
                ('from_cache', models.BooleanField(default=False)),
                ('model_used', models.CharField(blank=True, max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['class_no', 'subject'], name='tutor_doubt_class_n_f85eb7_idx'), models.Index(fields=['created_at'], name='tutor_doubt_created_827a53_idx')],
            },
        ),
    ]
