# Generated by Django 6.0.2 on 2026-02-28 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('pdf', 'NCERT PDF'), ('syllabus_json', 'Syllabus JSON')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('class_no', models.IntegerField(blank=True, null=True)),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of chunks indexed to Pinecone')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('filename', 'source_type')},
            },
        ),
    ]
